---
version: '3'
    
services:
    docker-registry:
        image: registry:2.7.0
        container_name: docker-registry
        ports:    
            - 5000:5000
        environment:
            REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
            REGISTRY_HTTP_TLS_KEY: /certs/domain.key
            REGISTRY_AUTH: htpasswd
            REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
            REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
        restart: always
        volumes:
            - ./volume:/var/lib/registry
            - ./certs:/certs
            - ./auth:/auth

    docker-registry-ui:
        image: konradkleine/docker-registry-frontend:v2
        container_name: registry-ui
        ports:
            - 8080:80
        environment: 
            ENV_DOCKER_REGISTRY_HOST: docker-registry
            ENV_DOCKER_REGISTRY_PORT: 5000 
            ENV_DOCKER_REGISTRY_USE_SSL: 1   

        restart: always